version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jellystack-portainer_server_1
      APP_PORT: 9000
      PROXY_AUTH_ADD: "true"

  server:
    image: portainer/portainer-ce:2.21.5
    restart: on-failure
    stop_grace_period: 30s
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${APP_DATA_DIR}/data/config:/data
