version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jellystack-flaresolverr_server_1
      APP_PORT: 8191
      PROXY_AUTH_ADD: "true"

  server:
    image: ghcr.io/flaresolverr/flaresolverr:v3.3.21
    restart: on-failure
    stop_grace_period: 30s
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=${TZ:-UTC}
