version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jellystack-sabnzbd_server_1
      APP_PORT: 8080
      PROXY_AUTH_ADD: "true"

  server:
    image: lscr.io/linuxserver/sabnzbd:4.4.1
    restart: on-failure
    stop_grace_period: 30s
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${JELLYSTACK_ROOT:-${UMBREL_ROOT}/JellyStack}:/data
