version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jellystack-audiobookshelf_server_1
      APP_PORT: 80
      PROXY_AUTH_ADD: "false"

  server:
    image: ghcr.io/advplyr/audiobookshelf:2.19.4
    restart: on-failure
    stop_grace_period: 30s
    environment:
      - TZ=${TZ:-UTC}
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${APP_DATA_DIR}/data/metadata:/metadata
      - ${JELLYSTACK_ROOT:-${UMBREL_ROOT}/JellyStack}/media/audiobooks:/audiobooks
      - ${JELLYSTACK_ROOT:-${UMBREL_ROOT}/JellyStack}/media/books:/books:ro
