version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jellystack-janitorr_server_1
      APP_PORT: 8978
      PROXY_AUTH_ADD: "true"

  server:
    image: ghcr.io/schaka/janitorr-jvm-stable:latest
    restart: on-failure
    stop_grace_period: 30s
    environment:
      - TZ=${TZ:-UTC}
      - JAVA_TOOL_OPTIONS=-Xmx512M
    volumes:
      - ${APP_DATA_DIR}/data/config/application.yml:/workspace/application.yml
      - ${APP_DATA_DIR}/data/logs:/logs
      - ${JELLYSTACK_ROOT:-${UMBREL_ROOT}/JellyStack}/media:/media
