version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: jellystack-jdownloader_server_1
      APP_PORT: 5800
      PROXY_AUTH_ADD: "true"

  server:
    image: jlesage/jdownloader-2:v25.10.1
    restart: on-failure
    stop_grace_period: 30s
    environment:
      - USER_ID=${PUID:-1000}
      - GROUP_ID=${PGID:-1000}
      - TZ=${TZ:-UTC}
      - KEEP_APP_RUNNING=1
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${JELLYSTACK_ROOT:-${UMBREL_ROOT}/JellyStack}/downloads/direct:/output
